---
- hosts: all
  tasks:
    - name: Install software-properties-common (prerequisite for Ruby install)
      apt:
        name: software-properties-common

    - name: Add Brightbox APT repository (prerequisite for Ruby install)
      apt_repository:
        repo: ppa:brightbox/ruby-ng
        state: present

    - name: Add PGDG APT repository (prerequisite for Postgres 9.6)
      shell: sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'

    - name: Add PGDG APT key (prerequisite for Postgres 9.6)
      apt_key:
        url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
        state: present

    - name: Update APT cache
      apt:
        update_cache: yes

    - name: Install Ruby 2.6
      apt:
        name: ruby2.6

    - name: Set Ruby 2.6 as the system default
      file:
        src: /usr/bin/ruby2.6
        dest: /usr/bin/ruby
        state: link

    - name: Make sure Ruby gem command is using Ruby 2.6
      file:
        src: /usr/bin/gem2.6
        dest: /usr/bin/gem
        state: link

    - name: Install Ruby 2.6 dev package (required for some application dependencies like ffi)
      apt:
        name: ruby2.6-dev

    - name: Install Postgres 9.6
      apt:
        name: postgresql-9.6

    - name: Install Postgres 9.6 server development package
      apt:
        name: postgresql-server-dev-9.6

    - name: Install gcc (required by make)
      apt:
        name: gcc

    - name: Install make (required by bundler)
      apt:
        name: make
 
    - name: Install Ruby Bundler
      shell: sudo gem install bundler -v 1.17.3

    - name: Install app-specific gems using Bundler v1.17.3
      shell: bundle _1.17.3_ update
      args:
        chdir: /vagrant

    # for some reason bundler is not installing rails in a way that is usable...
    - name: Install rails 4.2.11.3
      shell: sudo gem install rails -v 4.2.11.3
      args:
        chdir: /vagrant

    - name: Install NodeJS (javascript runtime for use by Rails)
      apt:
        name: nodejs

    - name: Set up database for dev and test environments
      command: /bin/bash db_setup.sh
      args:
        chdir: /vagrant/vagrant-ansible/scripts/
      notify:
      - Restart Postgres

    - name: Install Heroku Toolbelt
      shell: wget -O- https://toolbelt.heroku.com/install-ubuntu.sh | sh

  handlers:
    - name: Restart Postgres
      service:
        name: postgresql
        state: restarted

