development:
  secret_key_base: 9ac2d0ad8ebcc312090e99d745006d3cf887fa8sd78f8e1

test:
  secret_key_base: a1580ad61ccb6ac60f9f256948cf63d6e20akfw923823i8

# Do not keeddp production secrets in the repository,
# instead read values from the environment.
production:
  secret_token: <%= ENV["SECRET_TOKEN"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>